[project]
name = "graph_explorer_platform"
version = "0.1"
description = "Graph Explorer Platform"
dependencies = [
    "graph_exploerer_api==0.1"
]


[tool.setuptools]
provides = ["graph_explorer_platform"]
