[project]
name = "graph_explorer"
version = "0.1"
description = "Graph Explorer"
dependencies = [
    "graph_explorer_platform>=0.1",
    "Django>=5.1.3"
]

[tool.setuptools]
packages = ["graph_explorer"]